### PR TITLE
OSGi -enhancement - Use bnd-maven-plugin for better osgi support

### PR DESCRIPTION
**Pull request by stbischof**
Signed-off-by: Stefan Bischof <stbischof@bipolis.org>

### CODE REVIEW

**Comment by stbischof** [comment]
could you have a look on this?
Especially the way of auto-generating the module-info.class

What are the needs to build this as an module and not just as an simple jar?

**Comment by FDelporte** [comment]
Removing the module-info.java files will break the creation of the java modules, so this won't be a good approach... unfortunately I don't have enough OSGI experience to know how to support both modules and OSGI.

@savageautomate @eitch you don't happen to have the right knowledge regarding this topic?

**Comment by stbischof** [comment]
The module-info.java is automatically generated from the export and provideservice annotations.

**Comment by eitch** [comment]
So i of course like the idea of supporting OSGi, but one thing that won't work now is the fixed versioning in the code. The annotations in the package-info.java files are hard coded and we use mvn versions:set which probably wouldn't change these files. 

Could you maybe find a solution to auto-generate the package-info files with the current version?

**Comment by eitch** [comment]
@stbischof did you not find an idea on how to handle the package-info classes?

**Comment by stbischof** [comment]
Nope. And i had a deeper look into your plugin structure. I think it is better for me to to that with eclipse kura.

**Comment by FDelporte** [comment]
@stbischof thanks for the feedback! Kura seems indeed good solution for OSGi approach

**Pull request closed without merging**
