### PR TITLE
Add new IO type and providers and interface  Sensor

### PR DESCRIPTION
**Pull request by taartspi**
This add support into the pi4j-core.  It is a new IO type  Sensor. also defines an interface Sensor, Config/builder and provider.

There exist https://github.com/taartspi/Pi4J_V2-TemperatureSensor      This implements an I2C device that uses a BMP280 sensor, requiring this branch.  This branch also documents connecting an Adafruit BMP280 to a Pi.

### CODE REVIEW

**Comment by taartspi** [comment]
@FDelporte       Good day.   I don't see the proper way to connect this pull request to the issue 197.   You have a quick pointer on doing this ?        thanks Tom

**Comment by FDelporte** [comment]
I'm not really sure about this PR. It brings in a specific use-case/device, something that we removed when moving from V1 to V2 to improve maintainability. What do you think @eitch @savageautomate ?

**Comment by FDelporte** [comment]
Relates to #197

**Comment by taartspi** [comment]
Determined this code change is too specific to only two sensor types.  Suggested this implementation could define only the generic interfaces of possible  sensor types. Suggested ENUM be used.

**Pull request closed without merging**
